### ISSUE TITLE
RSS for blog

### ISSUE THREAD

**Issue by IRus** [avwie/avwie.github.io#1]
Hi! 

I wonder if you mind [and RSS to your blog](https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-an-rss-feed/)?

**Comment by avwie** [comment]
Good idea!
Done!

**Comment by IRus** [comment]
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/493656/163421156-3eee0537-d384-4819-ac0e-ee10dd4a66e0.png">
Look awesome, thank you!
